#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DeepTuneIO — Module 05: SLURM seff Metrics Extractor

Suggested filename:
    05_extract_seff_metrics.py

Article:
    Parallel I/O Analysis in Distributed Deep Learning Applications on
    High-Performance Computing

Authors:
    Edixon Parraga
    Betzabeth León
    Sandra Méndez
    Dolores Rexachs
    Emilio Luque

Purpose:
    Parse SLURM seff text reports and enrich the JobID metadata CSV generated by
    Module 03 with CPU, memory, node, core and job-state information.

Pipeline position:
    03_extract_jobids_from_parser.py  ->  JobID metadata CSV
    04_collect_seff_reports.py        ->  raw/seff/*.txt
    05_extract_seff_metrics.py        ->  enriched CSV with seff metrics

Input:
    1) JobID metadata CSV generated by Module 03
    2) Directory containing raw/seff/*.txt reports generated by Module 04

Output:
    CSV file containing the original metadata plus the extracted seff metrics.

Example:
    python 05_extract_seff_metrics.py \
        --input-csv /path/Data/DeepGalaxy/bw512/lustre_1ost/results/1_A_jobid_format_data_DeepGalaxy_Parser_bw512_lustre_1ost_JSC24.csv \
        --seff-dir /path/Data/DeepGalaxy/bw512/lustre_1ost/raw/seff \
        --output-dir /path/Data/DeepGalaxy/bw512/lustre_1ost/results \
        --application DeepGalaxy \
        --dataset-label bw512 \
        --scenario lustre_1ost \
        --event JSC24

Last update:
    August 2026
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Optional

import pandas as pd

VERSION = "2.0.0"


@dataclass
class SeffMetrics:
    """Metrics extracted from a single SLURM seff report."""

    seff_file: Optional[str] = None
    seff_path: Optional[str] = None
    seff_jobid: Optional[str] = None
    cluster: Optional[str] = None
    user_group: Optional[str] = None
    state: Optional[str] = None
    nodes: Optional[int] = None
    cores_per_node: Optional[int] = None
    cores: Optional[int] = None
    cpu_utilized_raw: Optional[str] = None
    cpu_utilized_seconds: Optional[float] = None
    cpu_efficiency_pct: Optional[float] = None
    core_walltime_raw: Optional[str] = None
    core_walltime_seconds: Optional[float] = None
    job_wallclock_raw: Optional[str] = None
    job_wallclock_seconds: Optional[float] = None
    memory_utilized_raw: Optional[str] = None
    memory_utilized_bytes: Optional[float] = None
    memory_efficiency_pct: Optional[float] = None
    total_memory_requested_raw: Optional[str] = None
    total_memory_requested_bytes: Optional[float] = None
    seff_status: str = "missing"
    seff_message: str = "seff_report_not_found"


def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Parse SLURM seff reports and enrich the JobID metadata CSV. "
            "Paths can be built automatically from the CORA/DeepTuneIO campaign hierarchy."
        )
    )

    # ------------------------------------------------------------------
    # Dynamic campaign hierarchy
    # ------------------------------------------------------------------
    parser.add_argument(
        "--campaign-root",
        type=Path,
        default=None,
        help=(
            "Absolute campaign root. When provided, it takes precedence over "
            "--cora-root/--article-id/--application/--dataset-label/--scenario."
        ),
    )
    parser.add_argument(
        "--cora-root",
        type=Path,
        default=None,
        help=(
            "Root of CORA_RDR_UAB. Default: environment CORA_ROOT, otherwise "
            "/mnt/netapp1/Store_RES/home/res/resd01/resd01epp/CORA_RDR_UAB"
        ),
    )
    parser.add_argument(
        "--article-id",
        default=None,
        help=(
            "Article folder. Default: environment ARTICLE_ID, otherwise "
            "Article_01_Parallel_IO_Analysis."
        ),
    )

    parser.add_argument(
        "--application",
        required=False,
        default=None,
        help="Application/benchmark, e.g. DeepGalaxy or DLIOv1.",
    )
    parser.add_argument(
        "--dataset-label",
        required=False,
        default=None,
        help=(
            "Dataset/configuration group, e.g. DG_bw512_f3c5x64, "
            "HDF5_64bs, NPZ_64bs, TFRecord_256kts_64bs."
        ),
    )
    parser.add_argument(
        "--scenario",
        required=False,
        default=None,
        help=(
            "Campaign scenario, e.g. lustre_1ost, lustre_2ost, "
            "lustre_4ost, nfs_SnGPU_e1 or lustre_ost."
        ),
    )
    parser.add_argument(
        "--event",
        default="JSC24",
        help="Event/publication campaign label used in output filenames.",
    )

    # ------------------------------------------------------------------
    # Explicit path overrides
    # ------------------------------------------------------------------
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=None,
        help=(
            "Explicit Module-03 CSV. If omitted it is discovered automatically "
            "inside the campaign results/Resource_Metadata or results directory."
        ),
    )
    parser.add_argument(
        "--seff-dir",
        type=Path,
        default=None,
        help=(
            "Explicit directory containing raw seff reports. "
            "Default: <campaign-root>/raw/seff."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=(
            "Explicit output directory. "
            "Default: <campaign-root>/results/Resource_Metadata."
        ),
    )

    parser.add_argument(
        "--output-file",
        default=None,
        help="Optional custom output CSV filename.",
    )
    parser.add_argument(
        "--jobid-column",
        default=None,
        help="Optional explicit JobID column name. Common variants are auto-detected.",
    )
    parser.add_argument(
        "--encoding",
        default="utf-8",
        help="Text encoding used to read seff files. Default: utf-8.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Return non-zero if one or more seff reports are missing/incomplete/error.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {VERSION}")

    return parser.parse_args(argv)


def resolve_campaign_paths(args: argparse.Namespace) -> dict[str, Path]:
    """Resolve all campaign paths without hard-coding an application.

    Precedence:
      1. explicit --campaign-root
      2. CORA hierarchy:
           <cora-root>/<article-id>/Data/<application>/<dataset-label>/<scenario>

    Individual --input-csv, --seff-dir and --output-dir override their defaults.
    """

    if args.campaign_root is not None:
        campaign_root = args.campaign_root.expanduser().resolve()
    else:
        if not args.application or not args.dataset_label or not args.scenario:
            raise ValueError(
                "When --campaign-root is not supplied, --application, "
                "--dataset-label and --scenario are required."
            )

        default_store = Path(
            "/mnt/netapp1/Store_RES/home/res/resd01/resd01epp"
        )
        cora_root = (
            args.cora_root
            or Path(os.environ.get("CORA_ROOT", default_store / "CORA_RDR_UAB"))
        )
        article_id = (
            args.article_id
            or os.environ.get("ARTICLE_ID", "Article_01_Parallel_IO_Analysis")
        )

        campaign_root = (
            Path(cora_root)
            / article_id
            / "Data"
            / args.application
            / args.dataset_label
            / args.scenario
        ).expanduser().resolve()

    seff_dir = (
        args.seff_dir.expanduser().resolve()
        if args.seff_dir is not None
        else campaign_root / "raw" / "seff"
    )

    output_dir = (
        args.output_dir.expanduser().resolve()
        if args.output_dir is not None
        else campaign_root / "results" / "Resource_Metadata"
    )

    if args.input_csv is not None:
        input_csv = args.input_csv.expanduser().resolve()
    else:
        # Module 03 v2 writes into Resource_Metadata by convention. For backward
        # compatibility, also inspect the older campaign results directory.
        search_dirs = [
            campaign_root / "results" / "Resource_Metadata",
            campaign_root / "results",
        ]

        candidates: list[Path] = []
        for directory in search_dirs:
            if directory.exists():
                candidates.extend(sorted(directory.glob("03_jobids_from_parser_*.csv")))
                candidates.extend(sorted(directory.glob("1_A_jobid_format_data_*.csv")))

        # Prefer exact campaign labels if available.
        exact_tokens = [
            str(args.application or ""),
            str(args.dataset_label or ""),
            str(args.scenario or ""),
        ]
        matching = [
            p for p in candidates
            if all(token in p.name for token in exact_tokens if token)
        ]

        selected = matching or candidates
        if len(selected) == 1:
            input_csv = selected[0].resolve()
        elif len(selected) == 0:
            expected = (
                campaign_root
                / "results"
                / "Resource_Metadata"
                / "03_jobids_from_parser_<application>_<dataset>_<scenario>_<event>.csv"
            )
            raise FileNotFoundError(
                "No Module-03 JobID metadata CSV could be discovered. "
                f"Expected under {expected.parent} or {campaign_root / 'results'}."
            )
        else:
            names = "\n  ".join(str(p) for p in selected)
            raise RuntimeError(
                "Multiple candidate Module-03 CSV files were found. "
                "Use --input-csv to select one explicitly:\n  " + names
            )

    return {
        "campaign_root": campaign_root,
        "input_csv": input_csv,
        "seff_dir": seff_dir,
        "output_dir": output_dir,
    }


def normalize_jobid(value: object) -> Optional[str]:
    """Normalize a JobID read from CSV or seff text."""
    if value is None:
        return None
    text = str(value).strip()
    if not text or text.lower() == "nan":
        return None
    # Avoid values such as 123456.0 when pandas inferred float.
    if re.fullmatch(r"\d+\.0", text):
        text = text[:-2]
    match = re.search(r"\d+", text)
    return match.group(0) if match else None


def find_jobid_column(df: pd.DataFrame, explicit_column: Optional[str] = None) -> str:
    """Find the JobID column in a DataFrame."""
    if explicit_column:
        if explicit_column not in df.columns:
            raise ValueError(f"Explicit JobID column not found: {explicit_column}")
        return explicit_column

    candidates = ["JobID", "jobid", "job_id", "JOBID", "slurm_jobid", "SLURM_JOB_ID"]
    for candidate in candidates:
        if candidate in df.columns:
            return candidate

    lower_map = {col.lower(): col for col in df.columns}
    for candidate in candidates:
        if candidate.lower() in lower_map:
            return lower_map[candidate.lower()]

    raise ValueError(
        "No JobID column found. Expected one of: " + ", ".join(candidates)
    )


def parse_hms_to_seconds(raw: Optional[str]) -> Optional[float]:
    """Convert SLURM time strings to seconds.

    Supported forms include:
        SS
        MM:SS
        HH:MM:SS
        D-HH:MM:SS
    """
    if not raw:
        return None

    text = raw.strip()
    if not text or text.lower() in {"unknown", "nan", "none"}:
        return None

    days = 0
    if "-" in text:
        day_part, text = text.split("-", 1)
        try:
            days = int(day_part)
        except ValueError:
            return None

    parts = text.split(":")
    try:
        values = [float(part) for part in parts]
    except ValueError:
        return None

    if len(values) == 3:
        hours, minutes, seconds = values
    elif len(values) == 2:
        hours, minutes, seconds = 0, values[0], values[1]
    elif len(values) == 1:
        hours, minutes, seconds = 0, 0, values[0]
    else:
        return None

    return days * 86400 + hours * 3600 + minutes * 60 + seconds


def parse_memory_to_bytes(raw: Optional[str]) -> Optional[float]:
    """Convert memory strings to bytes.

    Supported examples:
        514.55 GB
        528GB
        1024 MiB
        1.5 TB
        123456 bytes
    """
    if not raw:
        return None

    text = raw.strip().replace(",", "")
    if not text or text.lower() in {"unknown", "nan", "none"}:
        return None

    match = re.search(
        r"([0-9]+(?:\.[0-9]+)?)\s*(bytes?|b|kib|kb|mib|mb|gib|gb|tib|tb)",
        text,
        re.IGNORECASE,
    )
    if not match:
        return None

    value = float(match.group(1))
    unit = match.group(2).lower()

    multipliers = {
        "b": 1,
        "byte": 1,
        "bytes": 1,
        "kb": 1000,
        "mb": 1000**2,
        "gb": 1000**3,
        "tb": 1000**4,
        "kib": 1024,
        "mib": 1024**2,
        "gib": 1024**3,
        "tib": 1024**4,
    }
    return value * multipliers[unit]


def parse_percentage(raw: Optional[str]) -> Optional[float]:
    """Extract a percentage value from a string."""
    if not raw:
        return None
    match = re.search(r"([0-9]+(?:\.[0-9]+)?)\s*%", raw)
    return float(match.group(1)) if match else None


def first_match(pattern: str, text: str, flags: int = re.IGNORECASE | re.MULTILINE) -> Optional[str]:
    """Return first captured group for a regex pattern."""
    match = re.search(pattern, text, flags)
    return match.group(1).strip() if match else None


def parse_seff_report(seff_file: Path, encoding: str = "utf-8") -> SeffMetrics:
    """Parse one seff report and return normalized metrics."""
    try:
        text = seff_file.read_text(encoding=encoding, errors="replace")
    except OSError as exc:
        return SeffMetrics(
            seff_file=seff_file.name,
            seff_path=str(seff_file),
            seff_status="error",
            seff_message=f"cannot_read_file: {exc}",
        )

    if not text.strip():
        return SeffMetrics(
            seff_file=seff_file.name,
            seff_path=str(seff_file),
            seff_status="error",
            seff_message="empty_seff_report",
        )

    # Typical seff lines:
    # Job ID: 123456
    # Cluster: ft3
    # User/Group: user/group
    # State: COMPLETED (exit code 0)
    # Nodes: 4
    # Cores per node: 4
    # CPU Utilized: 01:23:45
    # CPU Efficiency: 96.92% of 01:25:00 core-walltime
    # Job Wall-clock time: 00:21:15
    # Memory Utilized: 514.55 GB
    # Memory Efficiency: 97.45% of 528.00 GB

    seff_jobid = normalize_jobid(first_match(r"^\s*Job\s*ID:\s*(.+)$", text))
    cluster = first_match(r"^\s*Cluster:\s*(.+)$", text)
    user_group = first_match(r"^\s*User/Group:\s*(.+)$", text)
    state = first_match(r"^\s*State:\s*(.+)$", text)

    nodes_raw = first_match(r"^\s*Nodes:\s*(\d+)", text)
    cores_per_node_raw = first_match(r"^\s*Cores\s*per\s*node:\s*(\d+)", text)
    cores_raw = first_match(r"^\s*Cores:\s*(\d+)", text)

    nodes = int(nodes_raw) if nodes_raw else None
    cores_per_node = int(cores_per_node_raw) if cores_per_node_raw else None
    cores = int(cores_raw) if cores_raw else None
    if cores is None and nodes is not None and cores_per_node is not None:
        cores = nodes * cores_per_node

    cpu_utilized_raw = first_match(r"^\s*CPU\s*Utilized:\s*(.+)$", text)
    cpu_efficiency_line = first_match(r"^\s*CPU\s*Efficiency:\s*(.+)$", text)
    job_wallclock_raw = first_match(r"^\s*Job\s*Wall-clock\s*time:\s*(.+)$", text)

    memory_utilized_raw = first_match(r"^\s*Memory\s*Utilized:\s*(.+)$", text)
    memory_efficiency_line = first_match(r"^\s*Memory\s*Efficiency:\s*(.+)$", text)

    core_walltime_raw = None
    if cpu_efficiency_line:
        match = re.search(r"of\s+(.+?)\s+core-walltime", cpu_efficiency_line, re.IGNORECASE)
        if match:
            core_walltime_raw = match.group(1).strip()

    total_memory_requested_raw = None
    if memory_efficiency_line:
        match = re.search(r"of\s+(.+)$", memory_efficiency_line, re.IGNORECASE)
        if match:
            total_memory_requested_raw = match.group(1).strip()

    # Some seff variants include an explicit line.
    explicit_total_mem = first_match(r"^\s*Total\s*Memory\s*Requested:\s*(.+)$", text)
    if explicit_total_mem:
        total_memory_requested_raw = explicit_total_mem

    messages: list[str] = []
    if not seff_jobid:
        messages.append("missing_jobid")
    if not state:
        messages.append("missing_state")
    if not cpu_efficiency_line:
        messages.append("missing_cpu_efficiency")
    if not memory_efficiency_line:
        messages.append("missing_memory_efficiency")

    status = "ok" if not messages else "incomplete"
    message = "seff_metrics_extracted" if not messages else ";".join(messages)

    return SeffMetrics(
        seff_file=seff_file.name,
        seff_path=str(seff_file),
        seff_jobid=seff_jobid,
        cluster=cluster,
        user_group=user_group,
        state=state,
        nodes=nodes,
        cores_per_node=cores_per_node,
        cores=cores,
        cpu_utilized_raw=cpu_utilized_raw,
        cpu_utilized_seconds=parse_hms_to_seconds(cpu_utilized_raw),
        cpu_efficiency_pct=parse_percentage(cpu_efficiency_line),
        core_walltime_raw=core_walltime_raw,
        core_walltime_seconds=parse_hms_to_seconds(core_walltime_raw),
        job_wallclock_raw=job_wallclock_raw,
        job_wallclock_seconds=parse_hms_to_seconds(job_wallclock_raw),
        memory_utilized_raw=memory_utilized_raw,
        memory_utilized_bytes=parse_memory_to_bytes(memory_utilized_raw),
        memory_efficiency_pct=parse_percentage(memory_efficiency_line),
        total_memory_requested_raw=total_memory_requested_raw,
        total_memory_requested_bytes=parse_memory_to_bytes(total_memory_requested_raw),
        seff_status=status,
        seff_message=message,
    )


def discover_seff_reports(seff_dir: Path) -> dict[str, Path]:
    """Build a JobID -> seff report path index."""
    reports: dict[str, Path] = {}
    for path in sorted(seff_dir.glob("*.txt")):
        # Prefer JobID embedded in the filename. If multiple numbers exist, the
        # SLURM JobID is usually the longest numeric token.
        numbers = re.findall(r"\d+", path.stem)
        if numbers:
            jobid = max(numbers, key=len)
            reports[jobid] = path
    return reports


def build_default_output_name(application: str, dataset_label: str, scenario: str, event: str) -> str:
    """Build the output filename following the pipeline naming convention."""
    return f"05_seff_metrics_{application}_{dataset_label}_{scenario}_{event}.csv"


def main(argv: Optional[list[str]] = None) -> int:
    args = parse_args(argv)

    try:
        paths = resolve_campaign_paths(args)
    except (ValueError, FileNotFoundError, RuntimeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    campaign_root = paths["campaign_root"]
    input_csv = paths["input_csv"]
    seff_dir = paths["seff_dir"]
    output_dir = paths["output_dir"]

    if not input_csv.exists():
        print(f"ERROR: input CSV does not exist: {input_csv}", file=sys.stderr)
        return 1

    if not seff_dir.exists():
        print(f"ERROR: seff directory does not exist: {seff_dir}", file=sys.stderr)
        return 1

    df = pd.read_csv(input_csv)
    jobid_column = find_jobid_column(df, explicit_column=args.jobid_column)

    seff_index = discover_seff_reports(seff_dir)
    output_records: list[dict[str, object]] = []

    # If campaign metadata was omitted because --campaign-root was used, try to
    # recover it from the Module-03 CSV without making it mandatory.
    application = args.application
    dataset_label = args.dataset_label
    scenario = args.scenario

    if application is None and "application" in df.columns and not df.empty:
        application = str(df.iloc[0]["application"])
    if dataset_label is None and "dataset_label" in df.columns and not df.empty:
        dataset_label = str(df.iloc[0]["dataset_label"])
    if scenario is None and "scenario" in df.columns and not df.empty:
        scenario = str(df.iloc[0]["scenario"])

    application = application or "unknown_application"
    dataset_label = dataset_label or "unknown_dataset"
    scenario = scenario or "unknown_scenario"

    print("DeepTuneIO — Module 05: SLURM seff Metrics Extractor")
    print(f"Campaign root : {campaign_root}")
    print(f"Application   : {application}")
    print(f"Scenario      : {scenario}")
    print(f"Dataset label : {dataset_label}")
    print(f"Input CSV     : {input_csv}")
    print(f"JobID column  : {jobid_column}")
    print(f"seff dir      : {seff_dir}")
    print(f"seff reports  : {len(seff_index)}")
    print(f"Rows          : {len(df)}")
    print(f"Output dir    : {output_dir}")

    for _, row in df.iterrows():
        base_record = row.to_dict()
        jobid = normalize_jobid(row.get(jobid_column))

        if not jobid:
            metrics = SeffMetrics(
                seff_status="missing",
                seff_message="missing_jobid_in_input_csv",
            )
        else:
            seff_file = seff_index.get(jobid)
            if seff_file is None:
                metrics = SeffMetrics(
                    seff_status="missing",
                    seff_message="seff_report_not_found",
                )
            else:
                metrics = parse_seff_report(seff_file, encoding=args.encoding)

        enriched_record = {**base_record, **asdict(metrics)}
        output_records.append(enriched_record)

    output_df = pd.DataFrame(output_records)
    output_dir.mkdir(parents=True, exist_ok=True)

    output_file = args.output_file or build_default_output_name(
        application=application,
        dataset_label=dataset_label,
        scenario=scenario,
        event=args.event,
    )
    output_path = output_dir / output_file
    output_df.to_csv(output_path, index=False)

    status_counts = output_df["seff_status"].value_counts(dropna=False).to_dict()
    ok = int(status_counts.get("ok", 0))
    incomplete = int(status_counts.get("incomplete", 0))
    missing = int(status_counts.get("missing", 0))
    errors = int(status_counts.get("error", 0))

    print("\nSummary")
    print(f"  OK         : {ok}")
    print(f"  Incomplete : {incomplete}")
    print(f"  Missing    : {missing}")
    print(f"  Errors     : {errors}")
    print(f"\nCSV saved to: {output_path}")

    if args.strict and (incomplete or missing or errors):
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
